Authorization implemented for admin dashboard JWT.
staynomad/admin-dashboard pull request #21
Opened 2021-08-25 00:16 UTC by KevinYuCode

# Relevant issue
 Issue Number: #193
Closes # (issue)

# Summary of change
- Added HTTP interceptor to send access and refresh tokens in the headers of every request.
- Implemented token verification after the user has logged into the dashboard.
- Added a logout button on the dashboard to allow users to log out of their session.
- Added refresh tokens to refresh the access tokens for the user each time they refresh the page

# Testing/Verification

- Try bypassing the password page by changing the URL
- Try bypassing the password page by using a fake token & refresh token value in your local storage.
- After logging in, try refreshing the page and see if you get a prompt to log in again (you shouldn't have to re-login if you have valid tokens.
- Try the logout button on the dashboard and see if your tokens are removed and check MongoDB if the refresh token is removed; therefore, you can't access the protected routes without logging in again.

2021-08-25 04:07 UTC, aidenszeto approved these changes
Works for me!

2021-08-26 01:21 UTC, nishantbalaji approved these changes
lgtm

2021-08-26 04:10 UTC, nishantbalaji requested changes
dont know if its just me but i get this all of a sudden 
![image](https://user-images.githubusercontent.com/44332326/130899228-33e17ed0-295a-48e1-916f-ae1c429a33d1.png)


shows up after i log in, and i can only open the site on my ip address, not localhost

![image](https://user-images.githubusercontent.com/44332326/130899781-4557856c-e0e0-4201-a700-e12dd3ea879d.png)

only breaks on this branch, main works fine?

2021-09-01 05:52 UTC, nishantbalaji approved these changes
lgtm

2021-09-02 15:01 UTC, merged